# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Deparment', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Qitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, verbose_name='问题')),
                ('answer', models.CharField(max_length=128, verbose_name='回答')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='问卷标题')),
                ('theme', models.CharField(max_length=64, verbose_name='主题')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.AddField(
            model_name='qitem',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='survey.Survey', verbose_name='Q1'),
        ),
        migrations.AddField(
            model_name='qitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='回答者'),
        ),
        migrations.AddField(
            model_name='deparment',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='调查表'),
        ),
    ]
