# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171101_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='调查表'),
        ),
    ]
