# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20171102_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyitemresult',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
