# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20171102_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtypedesc',
            name='typedesc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='内容'),
        ),
    ]
