# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20171102_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtypedesc',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='qitem',
            name='type',
            field=models.CharField(choices=[('single', '单选'), ('multi', '多选'), ('score', '评分1-10'), ('suggestion', '建议')], default='single', max_length=32, verbose_name='类型'),
        ),
    ]
